INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES(1, 'satish@gmail.com', 'Satish Kumar', '8822882', 'sat');

INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES(2, 'rupesh@gmail.com', 'Rupesh Kumar', '8112112', 'rup');